spring:
  application:
    name: Gobus
  datasource:
    url: jdbc:mysql://localhost:3307/gobus
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/

server:
  port: 8080
  servlet:
    session:
      timeout: 30m

logging:
  level:
    com.gobus: DEBUG
